### ISSUE TITLE
load all error

### ISSUE THREAD

**Issue by johnjohnsp1** [peewpw/Invoke-WCMDump#1]
Hello,
nice for sharing the code but once I try it I get this:

PS C:\temp\invoke-wcmdump> Invoke-WCMDump
Eccezione durante la chiamata di "LoadAll" con "0" argomento/i: "Failed to enumerate credentials"
In C:\temp\invoke-wcmdump\Invoke-WCMDump.ps1:252 car:5
+     $loadAll = [Credential]::LoadAll()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Exception

tested on VM Microsoft Windows 10 Pro N -  10.0.16299 with

PS C:\> $PSVersionTable.Values

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  98
Desktop
1      0      -1     -1
2      0      -1     -1
3      0      -1     -1
4      0      -1     -1
5      0      -1     -1
5      1      16299  98
10     0      16299  98
4      0      30319  42000
3      0      -1     -1
2      3      -1     -1
1      1      0      1

any idea ?

thanks

**Comment by peewpw** [comment]
This likely means you don't have any credentials saved. On my list to deliver a nicer error for that... If you add a credential to the cred manager and still get this, let me know.

**Comment by manasmbellani** [comment]
@peepw Confirmed - adding a domain credential shows the creds in the output, otherwise an error is shown.

**Comment by johnjohnsp1** [comment]
I can confirm once I type my credential inside the manager the program is working:

PS C:\temp\invoke-wcmdump> Invoke-WCMDump


Username         : test
Password         :
Target           : VM-WIN10
Description      :
LastWriteTime    : 12/12/2017 04:25:51
LastWriteTimeUtc : 12/12/2017 03:25:51
Type             : DomainPassword
PersistenceType  : Enterprise

but I doesn't show the password field, anything I still miss ?

thanks for the reply

**Comment by manasmbellani** [comment]
@johnjohnsp1 See the Readme. I have pasted the relevant part here: 

> Passwords are retrieved for "Generic" type credentials, but can not be retrived by the same method for "Domain" type credentials.

**Comment by johnjohnsp1** [comment]
confirmed by typing the "Generic Credential" it works, and not for the "Domain Credential":

PS C:\temp\Invoke-WCMDump-master> Invoke-WCMDump


Username         : administrator
Password         : prova123
Target           : homedc1.local
Description      :
LastWriteTime    : 12/12/2017 05:10:34
LastWriteTimeUtc : 12/12/2017 04:10:34
Type             : Generic
PersistenceType  : Enterprise

Username         : administrator
Password         :
Target           : homedc1.local
Description      :
LastWriteTime    : 12/12/2017 05:09:39
LastWriteTimeUtc : 12/12/2017 04:09:39
Type             : DomainPassword
PersistenceType  : Enterprise


thanks again for the explanation, was a totally my bad !
/cheers
